import { writeFile, mkdir } from 'node:fs/promises'
import { existsSync } from 'node:fs'

async function createPagesDynamicRoutes(numPages: number): Promise<void> {
  const pagesDir = `src/pages`
  const pagesDynamicRouteMdPath = `${pagesDir}/[page].md`
  const pagesDynamicRouteTsPath = `${pagesDir}/[page].paths.ts`

  if (!existsSync(pagesDir)) {
    await mkdir(pagesDir, { recursive: true })
  }

  await writeFile(
    pagesDynamicRouteMdPath,
    `\
---
layout: home
---
<!--
This file is auto-generated by src/.vitepress/theme/posts.data.ts
DO NOT EDIT THIS FILE DIRECTLY
-->
`
  )
  await writeFile(
    pagesDynamicRouteTsPath,
    `\
// This file is auto-generated by src/.vitepress/theme/posts.data.ts
// DO NOT EDIT THIS FILE DIRECTLY
export default {
  paths() {
    return Array.from({ length: ${numPages} }).map((_, i) => ({
      params: { page: String(i + 1) },
    }))
  },
}
`
  )
}

createPagesDynamicRoutes(2)
